//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.product = new HashSet<product>();
            this.outWarehourse = new HashSet<outWarehourse>();
            this.customerAddressInfo = new HashSet<customerAddressInfo>();
        }
    
        public string customerNum { get; set; }
        public string customerName { get; set; }
        public string phone { get; set; }
        public string chuanzhen { get; set; }
        public string email { get; set; }
        public string contents { get; set; }
        public System.DateTime createTime { get; set; }
        public int isDel { get; set; }
    
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<outWarehourse> outWarehourse { get; set; }
        public virtual ICollection<customerAddressInfo> customerAddressInfo { get; set; }
    }
}
