//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.LossReportDetails = new HashSet<LossReportDetails>();
            this.product = new HashSet<product>();
            this.outWareDetail = new HashSet<outWareDetail>();
            this.putWareDetail = new HashSet<putWareDetail>();
            this.transferDetail = new HashSet<transferDetail>();
            this.transferDetail1 = new HashSet<transferDetail>();
        }
    
        public string LocationNum { get; set; }
        public string LocationName { get; set; }
        public string warehourseNum { get; set; }
        public string barcode { get; set; }
        public int isDisable { get; set; }
        public int isDefult { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int isDel { get; set; }
    
        public virtual ICollection<LossReportDetails> LossReportDetails { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<outWareDetail> outWareDetail { get; set; }
        public virtual warehourse warehourse { get; set; }
        public virtual ICollection<putWareDetail> putWareDetail { get; set; }
        public virtual ICollection<transferDetail> transferDetail { get; set; }
        public virtual ICollection<transferDetail> transferDetail1 { get; set; }
    }
}
