//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CKSJKEntities : DbContext
    {
        public CKSJKEntities()
            : base("name=CKSJKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Company { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<customerAddressInfo> customerAddressInfo { get; set; }
        public DbSet<department> department { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<LossReport> LossReport { get; set; }
        public DbSet<LossReportDetails> LossReportDetails { get; set; }
        public DbSet<LossReportType> LossReportType { get; set; }
        public DbSet<OutboundType> OutboundType { get; set; }
        public DbSet<outWareDetail> outWareDetail { get; set; }
        public DbSet<outWarehourse> outWarehourse { get; set; }
        public DbSet<position> position { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<productLeix> productLeix { get; set; }
        public DbSet<putWareDetail> putWareDetail { get; set; }
        public DbSet<putWarehourse> putWarehourse { get; set; }
        public DbSet<receiptType> receiptType { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<supplier> supplier { get; set; }
        public DbSet<supplierLeix> supplierLeix { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<transfer> transfer { get; set; }
        public DbSet<transferDetail> transferDetail { get; set; }
        public DbSet<transferType> transferType { get; set; }
        public DbSet<warehourse> warehourse { get; set; }
    }
}
