//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class outWarehourse
    {
        public string OutboundNum { get; set; }
        public string OutboundTypeNum { get; set; }
        public string orderNo { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public string customerNum { get; set; }
        public string AddressNum { get; set; }
        public string ygNumber { get; set; }
        public System.DateTime createTime { get; set; }
        public long totalNum { get; set; }
        public double totalAmount { get; set; }
        public string examineState { get; set; }
        public string OperationMode { get; set; }
        public int isDel { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customerAddressInfo customerAddressInfo { get; set; }
        public virtual OutboundType OutboundType { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
