//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public position()
        {
            this.Staff = new HashSet<Staff>();
        }
    
        public string ZwNum { get; set; }
        public string ZwName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string title { get; set; }
        public int isDel { get; set; }
    
        public virtual position position1 { get; set; }
        public virtual position position2 { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
