//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.LossReportDetails = new HashSet<LossReportDetails>();
            this.outWareDetail = new HashSet<outWareDetail>();
            this.putWareDetail = new HashSet<putWareDetail>();
            this.transferDetail = new HashSet<transferDetail>();
        }
    
        public string productNum { get; set; }
        public string Probarcode { get; set; }
        public string productName { get; set; }
        public long productCount { get; set; }
        public double price { get; set; }
        public string Specifications { get; set; }
        public string productLeixNum { get; set; }
        public string CompanyNum { get; set; }
        public string contents { get; set; }
        public string LocationNum { get; set; }
        public string customerNum { get; set; }
        public int isDel { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual customer customer { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<LossReportDetails> LossReportDetails { get; set; }
        public virtual ICollection<outWareDetail> outWareDetail { get; set; }
        public virtual productLeix productLeix { get; set; }
        public virtual ICollection<putWareDetail> putWareDetail { get; set; }
        public virtual ICollection<transferDetail> transferDetail { get; set; }
    }
}
