//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class productLeix
    {
        public productLeix()
        {
            this.product = new HashSet<product>();
        }
    
        public string productLeixNum { get; set; }
        public string productLeixName { get; set; }
        public string Founder { get; set; }
        public System.DateTime createTime { get; set; }
        public string contents { get; set; }
        public int isDel { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
