//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.LossReport = new HashSet<LossReport>();
            this.outWarehourse = new HashSet<outWarehourse>();
            this.putWarehourse = new HashSet<putWarehourse>();
            this.transfer = new HashSet<transfer>();
        }
    
        public string ygNumber { get; set; }
        public string LoginName { get; set; }
        public string loginPwd { get; set; }
        public string ygName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int LoginNum { get; set; }
        public string BmNum { get; set; }
        public string ZwNum { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int isDel { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<LossReport> LossReport { get; set; }
        public virtual ICollection<outWarehourse> outWarehourse { get; set; }
        public virtual position position { get; set; }
        public virtual ICollection<putWarehourse> putWarehourse { get; set; }
        public virtual ICollection<transfer> transfer { get; set; }
    }
}
