//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehourse
    {
        public warehourse()
        {
            this.Location = new HashSet<Location>();
        }
    
        public string warehourseNum { get; set; }
        public string warehourseName { get; set; }
        public string warecode { get; set; }
    
        public virtual ICollection<Location> Location { get; set; }
    }
}
